### ISSUE TITLE
Limit the party size input field to number only

### ISSUE THREAD

**Issue by tjoengnguyen** [NateWr/restaurant-reservations#14]
Hi NateWr and contributors,

First of all, thanks for the time and effort you all spent on making such a wonderful plugin.

I'd like to ask if it's possible to only allow numeric values in the "party size" input field.
The second question is: if I add an extra input field (i.e phone number) in to the "Contact details fieldset", how can I make it a required field?

I look forward to hearing from you.
Cheers,
Tjoeng

**Comment by NateWr** [comment]
Hi Tjoeng,

The next version of Restaurant Reservations changes the Party field to a select dropdown and uses numbers only.

There should already be a phone number field in the Contact Details fieldset. If you want to make it required and perform some simple validation checks, you can install this [micro plugin](https://gist.github.com/NateWr/fedafb0be1989b4a0893).

**Comment by tjoengnguyen** [comment]
Hey Nate,

It's awesome to hear that you have taken the numeric Party input into account for the next version!
May I ask when will the next version be released?

Cheers,
Tjoeng

**Comment by NateWr** [comment]
@tjoengnguyen I hoped to release the next version weeks ago. There's an issue with the date and time pickers on iOS 8 that I'm hoping will be resolved soon so I can release it with the next version. But if it doesn't come soon I will just push the next version out anyway.

**Comment by tjoengnguyen** [comment]
Hi @NateWr, I wonder what is the date and time issue are you having with iOS 8? Maybe I am able to help you fix it. I see the date and time pickers working just fine on my iPhone 6 running iOS 8.

**Comment by NateWr** [comment]
Thanks @tjoengnguyen. Are you using the latest master from this GitHub repo or the latest stable version released on WordPress.org? The iOS 8 stuff is a bit complex. You can see the [bug report and resolution](https://github.com/amsul/pickadate.js/issues/523) in the pickadate.js library. The fix seems to be in place, but it led to [issues for other browsers](https://github.com/amsul/pickadate.js/issues/609). I tried to work around these problems, but someone I had test for me (I don't have an iOS 8 device) was still having problems. Can you try out [this form](http://scratch.themeofthecrop.com/booking-form/) and let me know how it works for you on iOS 8?

I know amsul, who manages the pickadate library, is working on a solution and that will be coming down the pipeline at some point. But I'm hesitant to delay the release of the next version of Restaurant Reservations for too long because it has a couple of big features (like adding/editing bookings from the backend).

**Comment by NateWr** [comment]
This was fixed in 1c5582e66651f078d895ef66aae90f3dbccfb359 and went out with version 1.3.
