### ISSUE TITLE
HELP: How to change title: Book a table

### ISSUE THREAD

**Issue by YostaScholten** [NateWr/restaurant-reservations#144]
Hi! I'm creating a website for children's parties and I really really want to change the title of this plugin because people can't make a reservation for a table but for a party. I think this plugin is very accessible so I would like to keep using this one (I have installed many others, none of them are useful in my situation).

Really hope you guys can help me out!

KR, Yosta

**Comment by JeePeeNL** [comment]
Hi Yosta,

You can change it in the translation file. 
Here is info on how to do that https://wplang.org/translate-theme-plugin/

You can find the translation files in /wp-content/plugins/restaurant-reservations/languages

Save your translated file back into /wordpress/wp-content/languages/plugins
Don't save it back into the original plugin folder because that will get deleted/overwritten with plugin updates.

JP

**Comment by YostaScholten** [comment]
Hi JP,

 

THANK YOU! This was so usefull! And fun to be honest. 

I downloaded the Poedit programm to do it. Also very accessible. Nice 😉

 

Thanks again!



Kind regards,

 

Yosta 

 

Van: John-Pierre Cornelissen <notifications@github.com> 
Verzonden: vrijdag 7 december 2018 17:49
Aan: NateWr/restaurant-reservations <restaurant-reservations@noreply.github.com>
CC: YostaScholten <yosta@volgerweg.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [NateWr/restaurant-reservations] HELP: How to change title: Book a table (#144)

 

Hi Yosta,

You can change it in the translation file.
Here is info on how to do that https://wplang.org/translate-theme-plugin/

You can find the translation files in /wp-content/plugins/restaurant-reservations/languages

Save your translated file back into /wordpress/wp-content/languages/plugins
Don't save it back into the original plugin folder because that will get deleted/overwritten with plugin updates.

JP
