### ISSUE TITLE
css in Footer

### ISSUE THREAD

**Issue by useb** [NateWr/restaurant-reservations#20]
any reason for loading a stylesheet in the footer?
it makes overriding impossible.

**Comment by NateWr** [comment]
Hi @useb, this is because the assets aren't enqueued on pages where the booking form doesn't exist. For this reason, we don't actually know whether or not the assets should be enqueued until the form is printed, which takes place after the `wp_enqueue_assets` action has fired.

If you want to enqueue them in the head on every page, you can add the following to your theme's `functions.php` file:

`
add_action( 'wp_enqueue_scripts', 'rtb_enqueue_assets', 20 );
`

If you just want help overriding a CSS style, send me a link and let me know. The CSS specificity is pretty low so it should be pretty easy to override anything you'd like by upping the specificity of the rule you're using.
