### ISSUE TITLE
Recapcha for booking form

### ISSUE THREAD

**Issue by jseutens** [NateWr/restaurant-reservations#39]
Is it possible to include the google recapcha above the submit button ?
same principal as on https://wordpress.org/plugins/contact-form-7/

**Comment by NateWr** [comment]
HI @jseutens, the plugin doesn't support this at the moment. You'd need to write your own integration with ReCaptcha. To this, you'll want to hook into the `$fields` array to add the custom field:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/Settings.class.php

Then you'll want to hook into the validation routine to check the validity of the Captcha value:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/Booking.class.php#L432

To be honest, I have not added any spam blocking features because users of the plugin haven't really reported significant problems with spam. I suspect this is because the unique scheduling rules make it hard for a spam bot to know a valid value for the date or time.
