### ISSUE TITLE
email always in spam

### ISSUE THREAD

**Issue by sunsgs** [NateWr/restaurant-reservations#70]
Hi there, either from customer or admin the emails always go into junk folder. Any help?

thanks

**Comment by NateWr** [comment]
Hi @sunsgs,

There are many things which can effect mail delivery. The FAQ includes a [5-step checklist](http://doc.themeofthecrop.com/plugins/restaurant-reservations/user/faq#no-emails) to narrow down the source of your problem.

If the issue is with your email server configuration, you'll find more detailed technical comments here:

https://wordpress.org/support/topic/e-mails-not-being-send?replies=6#post-8716463
